package com.boydti.fawe.example;

/**
 * Queues and applies lighting work generated by FAWE chunk changes.
 */
public interface Relighter {
    /**
     * Queue a complete chunk for relighting.
     *
     * @param cx chunk X
     * @param cz chunk Z
     * @param skipReason optional per-section optimization hints
     * @param bitmask section packet mask to resend after lighting
     * @return true if the relight request was accepted
     */
    boolean addChunk(int cx, int cz, byte[] skipReason, int bitmask);

    /**
     * Queue a single changed block for block-light propagation.
     */
    void addLightUpdate(int x, int y, int z);

    /**
     * Flush queued lighting without throwing into queue dispatch code.
     */
    void fixLightingSafe(boolean sky);

    default void removeAndRelight(boolean sky) {
        removeLighting();
        fixLightingSafe(sky);
    }

    /**
     * Clear pending lighting work.
     */
    void clear();

    /**
     * Remove stored light for queued chunks.
     */
    void removeLighting();

    /**
     * Flush queued block-light updates.
     */
    void fixBlockLighting();

    /**
     * Flush queued chunk skylight updates.
     */
    void fixSkyLighting();

    /**
     * @return true when no lighting work is pending
     */
    boolean isEmpty();

    public static class SkipReason {
        public static final byte NONE = 0;
        public static final byte AIR = 1;
        public static final byte SOLID = 2;
    }
}
